# Generated by Django 5.2.7 on 2025-10-26 13:30

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="api_key",
            field=fernet_fields.fields.EncryptedCharField(max_length=255),
        ),
    ]
